server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: firstModule
          uri: ${FIRST_SERVICE_HOST}
          predicates:
            - Path=/first-service/**
        - id: secondModule
          uri: ${SECOND_SERVICE_HOST}
          predicates:
            - Path=/second-service/**
        - id: frontliner
          uri: ${FRONTLINER_HOST}
          predicates:
            - Path=/
#        - id: auth
#          uri: http://localhost:8089/
#          predicates:
#            - Path=/api/auth/
#        - id: binar
#          uri: https://binaracademy.com/
#          predicates:
#            - Path=/**
