server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: firstModule
          uri: https://first-service-production.up.railway.app/
          predicates:
            - Path=/first-controller/**
        - id: secondModule
          uri: https://second-service-production.up.railway.app/
          predicates:
            - Path=/second-controller/**