server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: firstModule
          uri: http://localhost:8081/
          predicates:
            - Path=/first-controller/**
        - id: secondModule
          uri: http://localhost:8082/
          predicates:
            - Path=/second-controller/**